<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 2,
                'key' => 'document',
                'parent_key' => 'component',
                'local' => 'document',
                'text' => '文档',
                'target' => '_blank',
                'icon' => 'book',
                'path' => NULL,
                'url' => 'https://open.vbill.cn/react-admin',
                'order' => 1200,
                'type' => 1,
                'code' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'key' => 'menus',
                'parent_key' => '20190718090554vTy5a',
                'local' => 'menus',
                'text' => '菜单编辑',
                'target' => NULL,
                'icon' => 'menu-unfold',
                'path' => '/menu-permission',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'key' => 'codeGenerator',
                'parent_key' => 'component',
                'local' => 'codeGenerator',
                'text' => '代码生成',
                'target' => NULL,
                'icon' => 'code',
                'path' => '/admin-crud',
                'url' => NULL,
                'order' => 999,
                'type' => 1,
                'code' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'key' => 'ajax',
                'parent_key' => 'component',
                'local' => 'ajax',
                'text' => 'ajax请求',
                'target' => NULL,
                'icon' => 'api',
                'path' => '/example/ajax',
                'url' => NULL,
                'order' => 998,
                'type' => 1,
                'code' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'key' => 'user',
                'parent_key' => '20190718090554vTy5a',
                'local' => 'users',
                'text' => '用户列表',
                'target' => NULL,
                'icon' => 'user',
                'path' => '/users',
                'url' => NULL,
                'order' => 900,
                'type' => 1,
                'code' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'key' => 'role',
                'parent_key' => '20190718090554vTy5a',
                'local' => 'roles ',
                'text' => '角色列表',
                'target' => NULL,
                'icon' => 'team',
                'path' => '/roles',
                'url' => NULL,
                'order' => 800,
                'type' => 1,
                'code' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'key' => 'page404',
                'parent_key' => NULL,
                'local' => 'page404',
                'text' => '404页面不存',
                'target' => NULL,
                'icon' => 'file-search',
                'path' => '/404',
                'url' => NULL,
                'order' => 700,
                'type' => 2,
                'code' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'key' => 'user-center',
                'parent_key' => NULL,
                'local' => 'user-center',
                'text' => '用户中心',
                'target' => NULL,
                'icon' => 'user',
                'path' => '/user-center',
                'url' => NULL,
                'order' => 600,
                'type' => 1,
                'code' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'key' => 'component',
                'parent_key' => NULL,
                'local' => 'component',
                'text' => '组件',
                'target' => NULL,
                'icon' => 'ant-design',
                'path' => NULL,
                'url' => NULL,
                'order' => 700,
                'type' => 1,
                'code' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'key' => '/example/antd/async-select',
                'parent_key' => 'component',
                'local' => 'asyncSelect',
                'text' => 'AsyncSelect # 异步下拉',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/async-select',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'key' => '/example/antd/form-element',
                'parent_key' => 'component',
                'local' => 'formElement',
                'text' => 'FormElement # 表单元素',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/form-element',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'key' => '/example/antd/operator',
                'parent_key' => 'component',
                'local' => 'operator',
                'text' => 'Operator # 操作',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/operator',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'key' => '/example/antd/pagination',
                'parent_key' => 'component',
                'local' => 'pagination',
                'text' => 'Pagination # 分页组件',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/pagination',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'key' => '/example/antd/query-bar',
                'parent_key' => 'component',
                'local' => 'queryBar',
                'text' => 'QueryBar # 查询条',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/query-bar',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'key' => '/example/antd/query-item',
                'parent_key' => 'component',
                'local' => 'queryItem',
                'text' => 'QueryItem # 查询条件',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/query-item',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'key' => '/example/antd/table-editable',
                'parent_key' => 'component',
                'local' => 'tableEditable',
                'text' => 'TableEditable # 可编辑表格',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/table-editable',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'key' => '/example/antd/table-row-draggable',
                'parent_key' => 'component',
                'local' => 'tableRowDraggable',
                'text' => 'TableRowDraggable # 表格行可拖拽',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/table-row-draggable',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'key' => '/example/antd/tool-bar',
                'parent_key' => 'component',
                'local' => 'toolBar',
                'text' => 'ToolBar # 工具条',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/tool-bar',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'key' => '/example/antd/user-avatar',
                'parent_key' => 'component',
                'local' => 'userAvatar',
                'text' => 'UserAvatar # 用户头像',
                'target' => NULL,
                'icon' => 'deployment-unit',
                'path' => '/example/antd/user-avatar',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
            19 => 
            array (
                'id' => 51,
                'key' => '20190718090554vTy5a',
                'parent_key' => NULL,
                'local' => 'authManager',
                'text' => '权限管理',
                'target' => NULL,
                'icon' => 'lock',
                'path' => NULL,
                'url' => NULL,
                'order' => 2,
                'type' => 1,
                'code' => NULL,
            ),
            20 => 
            array (
                'id' => 52,
                'key' => '20190722021436W09iP',
                'parent_key' => '20190718090554vTy5a',
                'local' => 'administrator',
                'text' => '管理员管理',
                'target' => NULL,
                'icon' => 'usergroup-add',
                'path' => '/admins',
                'url' => NULL,
                'order' => 1000,
                'type' => 1,
                'code' => NULL,
            ),
        ));
        
        
    }
}